name: Run ATI.SU Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium-hub:
        image: selenium/hub:4.10.0
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome:4.10.0
        environment:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        depends_on:
          - selenium-hub

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install allure
        
    - name: Run tests
      env:
        ATI_API_TOKEN: ${{ secrets.ATI_API_TOKEN }}
        ATI_USER: ${{ secrets.ATI_USER }}
        ATI_PASSWORD: ${{ secrets.ATI_PASSWORD }}
        SELENIUM_HUB: http://selenium-hub:4444
      run: |
        pytest -v --alluredir=allure-results
        
    - name: Generate Allure report
      run: |
        allure generate allure-results -o allure-report --clean
        
    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report